package com.boot.dao;

import com.boot.model.Userinfo;

public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    int insertSelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    Userinfo selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    int updateByPrimaryKeySelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    int updateByPrimaryKey(Userinfo record);
}