package com.boot.model;

public class Userinfo {
    /**
     *aaaaaaaaaaaaa
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USERNAME
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.PASSWORD
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.DESCRI
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    private String descri;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USERNAME
     *
     * @return the value of USERINFO.USERNAME
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USERNAME
     *
     * @param username the value for USERINFO.USERNAME
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.PASSWORD
     *
     * @return the value of USERINFO.PASSWORD
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.PASSWORD
     *
     * @param password the value for USERINFO.PASSWORD
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.DESCRI
     *
     * @return the value of USERINFO.DESCRI
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    public String getDescri() {
        return descri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.DESCRI
     *
     * @param descri the value for USERINFO.DESCRI
     *
     * @mbg.generated Tue Dec 12 17:53:54 CST 2017
     */
    public void setDescri(String descri) {
        this.descri = descri;
    }
}