package com.boot.model;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbg.generated Mon Dec 18 23:12:46 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbg.generated Mon Dec 18 23:12:46 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.password
     *
     * @mbg.generated Mon Dec 18 23:12:46 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.descri
     *
     * @mbg.generated Mon Dec 18 23:12:46 CST 2017
     */
    private String descri;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbg.generated Mon Dec 18 23:12:46 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbg.generated Mon Dec 18 23:12:46 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbg.generated Mon Dec 18 23:12:46 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbg.generated Mon Dec 18 23:12:46 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.password
     *
     * @return the value of userinfo.password
     *
     * @mbg.generated Mon Dec 18 23:12:46 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.password
     *
     * @param password the value for userinfo.password
     *
     * @mbg.generated Mon Dec 18 23:12:46 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.descri
     *
     * @return the value of userinfo.descri
     *
     * @mbg.generated Mon Dec 18 23:12:46 CST 2017
     */
    public String getDescri() {
        return descri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.descri
     *
     * @param descri the value for userinfo.descri
     *
     * @mbg.generated Mon Dec 18 23:12:46 CST 2017
     */
    public void setDescri(String descri) {
        this.descri = descri;
    }
}